// Generated by https://quicktype.io

export interface IAccountReg {
    channeltype:             string | undefined;
    requestoridentification: string | undefined;
    deviceowner:             string | undefined;
    unitholderid:            string | undefined;
    firstname:               string | undefined;
    identificationtype:      string | undefined;
    identificationnumber:    number | undefined;
    agentcode:               string | undefined;
    branchcode:              string | undefined;
    uhcategory:              string | undefined;
    race:                    string | undefined;
    cellphonenumber:         number | undefined;
    telephone1:              number | undefined;
    addressline1:            string | undefined;
    addressline2:            string | undefined;
    addressline3:            string | undefined;
    addressline4:            string | undefined;
    otherinfo10:             string | undefined;
    zipcode:                 number | undefined;
    dateofbirth:             string | undefined;
    sex:                     string | undefined;
    occupation:              string | undefined;
    email:                   string | undefined;
    father_spousename:       string | undefined;
    otherinfo8:              number | undefined;
    occupationsector:        string | undefined;
    occupationcategory:      string | undefined;
    natureofbusiness:        string | undefined;
    companyname:             string | undefined;
    title:                   string | undefined;
    religion:                string | undefined;
    guardianid:              string | undefined;
    fatca:                   string | undefined;
    crs:                     string | undefined;
    participateinasnbmkt:    string | undefined;
    bankcode:                number | undefined;
    bankaccountnumber:       number | undefined;
    pep:                     string | undefined;
    lastupdatedate:          string | undefined;
    transactionchannel:      string | undefined;
    transactionstatus:       string | undefined;
    rejectcode:              string | undefined;
    rejectreason:            string | undefined;
}

export class AccountReg implements IAccountReg {
    channeltype:             string | undefined;
    requestoridentification: string | undefined;
    deviceowner:             string | undefined;
    unitholderid:            string | undefined;
    firstname:               string | undefined;
    identificationtype:      string | undefined;
    identificationnumber:    number | undefined;
    agentcode:               string | undefined;
    branchcode:              string | undefined;
    uhcategory:              string | undefined;
    race:                    string | undefined;
    cellphonenumber:         number | undefined;
    telephone1:              number | undefined;
    addressline1:            string | undefined;
    addressline2:            string | undefined;
    addressline3:            string | undefined;
    addressline4:            string | undefined;
    otherinfo10:             string | undefined;
    zipcode:                 number | undefined;
    dateofbirth:             string | undefined;
    sex:                     string | undefined;
    occupation:              string | undefined;
    email:                   string | undefined;
    father_spousename:       string | undefined;
    otherinfo8:              number | undefined;
    occupationsector:        string | undefined;
    occupationcategory:      string | undefined;
    natureofbusiness:        string | undefined;
    companyname:             string | undefined;
    title:                   string | undefined;
    religion:                string | undefined;
    guardianid:              string | undefined;
    fatca:                   string | undefined;
    crs:                     string | undefined;
    participateinasnbmkt:    string | undefined;
    bankcode:                number | undefined;
    bankaccountnumber:       number | undefined;
    pep:                     string | undefined;
    lastupdatedate:          string | undefined;
    transactionchannel:      string | undefined;
    transactionstatus:       string | undefined;
    rejectcode:              string | undefined;
    rejectreason:            string | undefined;

    constructor(data?: IAccountReg){
        if (data)
        {
            for (var property in data){
                if (data.hasOwnProperty(property)){
                    (<any>this)[property] = (<any>data)[property];
                }
            }
        }
    }

    init(data?: any){
        if (data){
            this.channeltype = data.result.channeltype;
            this.requestoridentification = data.result.requestoridentification;
            this.deviceowner = data.result.deviceowner;
            this.unitholderid = data.result.unitholderid;
            this.firstname = data.result.firstname;
            this.identificationtype = data.result.identificationtype;
            this.identificationnumber = data.result.identificationnumber;
            this.agentcode = data.result.agentcode;
            this.branchcode = data.result.branchcode;
            this.uhcategory = data.result.uhcategory;
            this.race = data.result.race;
            this.cellphonenumber = data.result.cellphonenumber;
            this.telephone1 = data.result.telephone1;
            this.addressline1 = data.result.addressline1;
            this.addressline2 = data.result.addressline2;
            this.addressline3 = data.result.addressline3;
            this.addressline4 = data.result.addressline4;
            this.otherinfo10 = data.result.otherinfo10;
            this.zipcode = data.result.zipcode;
            this.dateofbirth = data.result.dateofbirth;
            this.sex = data.result.sex;
            this.occupation = data.result.occupation;
            this.email = data.result.email;
            this.father_spousename = data.result.father_spousename;
            this.otherinfo8 = data.result.otherinfo8;
            this.occupationsector = data.result.occupationsector;
            this.occupationcategory = data.result.occupationcategory;
            this.natureofbusiness = data.result.natureofbusiness;
            this.companyname = data.result.companyname;
            this.title = data.result.title;
            this.religion = data.result.religion;
            this.guardianid = data.result.guardianid;
            this.fatca = data.result.fatca;
            this.crs = data.result.crs;
            this.participateinasnbmkt = data.result.participateinasnbmkt;
            this.bankcode = data.result.bankcode;
            this.bankaccountnumber = data.result.bankaccountnumber;
            this.pep = data.result.pep;
            this.lastupdatedate = data.result.lastupdatedate;
            this.transactionchannel = data.result.transactionchannel;
            this.transactionstatus = data.result.transactionstatus;
            this.rejectcode = data.result.rejectcode;
            this.rejectreason = data.result.rejectreason;
        }
    }


    static fromJS(data: any): AccountReg {
        let result = new AccountReg();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
       data = typeof data === 'object' ? data : {};
       data["channeltype"] = this.channeltype;
       return data;
    }

    clone(): AccountReg {
        const json = this.toJSON();
        let result = new AccountReg();
        result.init(json);
        return result;
    }

}
